FROM node:16.17.0-alpine AS builder
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY . /app

# Copy file env-development.example ke .env
COPY env-development.example /app/.env

# Ganti title di index.html
RUN sed -i 's/<title>PNM Maps<\/title>/<title>PNM Maps - Development<\/title>/g' /app/public/index.html

RUN npm i

ENV NODE_ENV development
RUN npm run build

# production environment
FROM nginx:1.23.2-alpine
COPY --from=builder /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
